version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quiz-game-db
    environment:
      POSTGRES_DB: quiz_game
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
