version: '3.8'

# Дополнительные сервисы мониторинга для Quiz Game
services:
  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: quiz-game-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:9090'
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

  # Grafana для визуализации метрик
  grafana:
    image: grafana/grafana:latest
    container_name: quiz-game-grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_COOKIE_SECURE: false
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

  # Node Exporter для системных метрик
  node-exporter:
    image: prom/node-exporter:latest
    container_name: quiz-game-node-exporter
    ports:
      - "127.0.0.1:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

  # Loki для сбора логов
  loki:
    image: grafana/loki:latest
    container_name: quiz-game-loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./config/loki/loki.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

  # Promtail для отправки логов в Loki
  promtail:
    image: grafana/promtail:latest
    container_name: quiz-game-promtail
    volumes:
      - ./config/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - logs_prod:/logs:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

  # Alertmanager для уведомлений
  alertmanager:
    image: prom/alertmanager:latest
    container_name: quiz-game-alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
      - quiz-network
    security_opt:
      - no-new-privileges:true

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  quiz-network:
    external: true
